print("Welcome to the School Resources Assessment Program!\n")
print("Location: Bayview Glen\n")
print("1. Water Fountains: ")
numf = int(input("  -Enter the number of water fountains: "))
locf = input("  -Enter the locations of the water fountains (separated by commas): ")
conf = input("  -Describe the condition of the water fountains: ")
print("2. Washrooms: ")
numw = int(input("  -Enter the number of washrooms: "))
locw = input("  -Enter the locations of the washrooms (separated by commas): ")
conw = input("  -Describe the cleanliness of the washrooms: ")
print("3. Common Areas: ")
numc = int(input("  -Enter the number of common areas: "))
locc = input("  -Enter the locations of the common areas (separated by commas): ")
conc = input("  -Describe the condition of the common areas: ")
print("4. Gyms: ")
numg = int(input("  -Enter the number of gyms: "))
locg = input("  -Enter the locations of the gyms (separated by commas): ")
cong = input("  -Describe the condition of the gyms: ")
print("5. Classrooms: ")
numcl = int(input("  -Enter the number of classrooms: "))

fpercl = float(numf)/float(numcl)
wpercl = float(numw)/float(numcl)
cpercl = float(numc)/float(numcl)
gpercl = float(numg)/float(numcl)

print("RESOURCE ANALYSIS")
print("1. Water Fountains")
print(f"  -Number of water fountains: {numf}")
print(f"  -Location of water fountains: {locf}")
print(f"  -Condition: {conf}")
print("2. Washrooms")
print(f"  -Number of washrooms: {numw}")
print(f"  -Location of the washrooms: {locw}")
print(f"  -Cleanliness: {conw}")
print("3. Common Areas")
print(f"  -Number of common areas: {numc}")
print(f"  -Location of common areas: {locc}")
print(f"  -Condition: {conc}")
print("4. Gyms")
print(f"  -Number of gyms: {numg}")
print(f"  -Location of gyms: {locg}")
print(f"  -Condition: {cong}")
print("5. Classrooms")
print(f"  -Number of classrooms: {numcl}")
print(f"  -Number of fountains per classroom: {fpercl}")
print(f"  -Number of washrooms per classroom: {wpercl}")
print(f"  -Number of common areas per classroom: {cpercl}")
print(f"  -Number of gyms per classroom: {gpercl}")