int1 = float(input("Input int #1: "))
int2 = float(input("Input int #2: "))
sum = round(int1+int2,2)
product = round(int1*int2,2)
quotient = round(int1/int2,2)
difference = round(int1-int2,2)
print(f"Sum: {sum}")
print(f"Product: {product}")
print(f"Quotient: {quotient}")
print(f"DIfference: {difference}")